### PR TITLE
Update LIBDIR to LIB_DIR in Makefile

### PR DESCRIPTION
**Pull request by semicolonpoundpound**

### CODE REVIEW

**Comment by Ada-Codina** [comment]
Hi @semicolonpoundpound can you resolve the DCO issue from the Checks tab?

**Comment by semicolonpoundpound** [comment]
Hi,

I am going to close that one as it seems just redoing the commit with a signed commit is easier. I did that through github.com and don't see a way to change that.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by semicolonpoundpound** [comment]
Check that, it should be upated.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by semicolonpoundpound** [comment]
I have no idea how commit b20667f ended up there.  That isn't my commit.  I think I am going to refork this and make the change with a new repo.

**Pull request closed without merging**
